### ISSUE TITLE
[Units] Use `modify_unit_type` instead of duplicating units

### ISSUE THREAD

**Issue by knyghtmare** [schilffarth/wesnoth-deception#1]
Instead of `Deception Orcish Archer`, `Deception Orcish Crossbowman`, you can use `[modify_unit_type]` to add the advancement of `Orcish Sharpshooter` to the core Orcish Crossbowman in your campaign directly.

```ini
[campaign]
    [modify_unit_type]
         type=Orcish Crossbowman
         add_advancement=Orcish Sharpshooter
    [/modify_unit_type]
[/campaign]
```

**Comment by schilffarth** [comment]
Thank you, I added it to the _main file and adjusted all scenario files to use the core unit types.  :)
